# Hunter Harris 8-23-2021
# Haskell Day 1
# Makefile

make_haskell:
	# ghc -o hello hello.hs
	ghc -o hailstone hailstone.hs

clean:
	# rm hello hello.hi hello.o
	rm hailstone hailstone.hi hailstone.o
