# Hunter Harris 8-23-2021
# Haskell Day 1
# Makefile

make_haskell:
	# ghc -Wall lecture2.hs
	ghc -Wall LogAnalysis.hs

clean:
	# rm lecture2 lecture2.hi lecture2.o
	rm LogAnalysis.o LogAnalysis.hi Log.o Log.hi
